name: haven

# use:
# prefer micromamba (conda takes much longer, if ever, to solve)
# micromamba installed in ~30s
#   date; micromamba create -y -n haven -f ./environment.yml; date
#   # then activate with:
#   eval "$(micromamba shell hook --shell=bash)"
#   micromamba activate haven
# conda installed in ~250s
#   date; conda env create --force -f ./environment.yml; date
#   # then activate with:
#   conda activate haven

variables:
  PYDM_DEFAULT_PROTOCOL: ca

channels:
  - conda-forge
  - defaults
  - aps-anl-tag
  - nsls2forge

dependencies:
  # --- Python core packages
  - python=3.10
  - ipython
  - ipykernel
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - psutil

  # --- testing and quality assurance
  - black
  - flake8
  - pre-commit
  - pylint
  - pytest
  - pytest-cov
  - pytest-qt >=4.2.0
  - pytest-mock
  - caproto >=1.0.0
  # - pytest-notebook

  # Database management
  - pymongo
  - databroker-pack
  - databroker =1.2

  # --- Qt
  - pyqt >=5.12
  - qt >=5.12
  - qtawesome

  # --- general support packages
  - bitshuffle
  - epics-base >=7.0.5
  - h5py
  - hdf5plugin
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pyEpics >=3.5.0
  - scikit-image
  - xlrd

  # --- Bluesky framework packages
  - adl2pydm
  - apstools
  - area-detector-handlers
  - bluesky-queueserver
  - bluesky-queueserver-api
  - bluesky-widgets
  - bluesky >=1.8.1
  # - happi
  # - hklpy >=1.0.3  # --- linux-64
  - ophyd >=1.6.3
  - pydm >=1.16.0
  # - tiled-server
  # https://github.com/pydata/xarray/issues/6818
  - xarray !=2022.6.0  # incompatible with numpy=1.20

  # --- user-requested packages
  - aps-dm-api >=5   # linux-64  osx-64
  # - c2dataviewer  # --- linux-64
  # - nexpy
  # - punx
  # - pvapy
  - mergedeep
  - pvview
  # - pymca
  - pyRestTable
  # - spec2nexus
  - stdlogpj
  - tqdm
  - xraydb
  - xrayutilities
  - pyviz_comms
  - hvplot
  
  # --- packaging and publishing
  # - conda-build
  - coverage
  - poetry
  - sphinx
  - pandoc
  - nbsphinx
  - graphviz
  - sphinxcontrib-napoleon
  # - twine
  # - versioneer
  # - mamba
  # - micromamba
  # - pygithub

  - pip:
    - time-machine
    - autoapi
    - pytest-mongodb
    # - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
    # --- optional Bluesky framework packages for evaluation
    # - bluesky-webclient is NOT Python software, don't install it this way
    #    https://github.com/bluesky/bluesky-webclient
