name: haven

# use:
# prefer micromamba (conda takes much longer, if ever, to solve)
# micromamba installed in ~30s
#   date; micromamba create -y -n haven -f ./environment.yml; date
#   # then activate with:
#   eval "$(micromamba shell hook --shell=bash)"
#   micromamba activate haven
# conda installed in ~250s
#   date; conda env create --force -f ./environment.yml; date
#   # then activate with:
#   conda activate haven

variables:
  PYDM_DEFAULT_PROTOCOL: ca

channels:
  - conda-forge
  - defaults
  - aps-anl-tag
  - nsls2forge

dependencies:
  # --- Python core packages
  - python=3.9  # Until this is fixed in pydm: https://github.com/slaclab/pydm/issues/951
  - ipython
  - ipykernel
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - psutil
  - numba>=0.56  # Ensures 0.53 (broken) isn't installed

  # --- testing and quality assurance
  - black >=24
  - flake8
  - pre-commit
  - pylint
  - pytest
  - pytest-cov
  - pytest-qt >=4.2.0
  - pytest-xvfb
  - pytest-mock
  - pytest-asyncio
  - caproto >=1.0.0
  # - pytest-notebook

  # Database management
  - pymongo
  - databroker-pack
  - databroker =1.2.5

  # --- Qt
  # Pin at 5.12.3 until pydm figures out how to designer widgets
  - pyqt ==5.12.3
  - pyqtgraph < 0.13.0  # Last version to support pyqt 5.12
  # - pyqt >=5.12, <5.13  
  - qt >=5.12
  - qtawesome

  # --- general support packages
  - bitshuffle
  - epics-base >=7.0.5
  - h5py
  - hdf5plugin
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pyEpics >=3.5.0
  - scikit-image
  - xlrd
  - peakutils

  # XES analysis packages
  - scikit-learn
  - kneed

  # --- Bluesky framework packages
  - adl2pydm
  - apstools >=1.6.16
  - area-detector-handlers
  - bluesky-queueserver
  - bluesky-queueserver-api
  - bluesky-widgets
  - bluesky-adaptive
  - bluesky >=1.8.1
  # - happi
  # - hklpy >=1.0.3  # --- linux-64
  - ophyd >=1.6.3
  - pcdsdevices  # For extra signal types
  - pydm >=1.18.0
  - typhos
  - p4p
  - tiled-server
  - tiled-client >= 0.1.0a106  # 2023-10-02 to get new Cache() behavior
  - pydantic >=1.8.2,<2  # tiled fails with pydantic 2
  # https://github.com/pydata/xarray/issues/6818
  - xarray !=2022.6.0  # incompatible with numpy=1.20

  # --- user-requested packages
  - aps-dm-api >=5   # linux-64  osx-64
  # - c2dataviewer  # --- linux-64
  # - nexpy
  # - punx
  # - pvapy
  - mergedeep
  - pvview
  # - pymca
  - pyRestTable
  # - spec2nexus
  - stdlogpj
  - tqdm
  - xrayutilities
  - pyviz_comms
  - hvplot
  
  # --- packaging and publishing
  # - conda-build
  - build
  - twine
  - coverage
  - poetry
  - sphinx
  - pandoc
  - nbsphinx
  - graphviz
  - sphinxcontrib-napoleon
  # - versioneer
  # - mamba
  # - micromamba
  # - pygithub

  - pip:
    - aioca
    - apsbss
    - time-machine
    - autoapi
    - pytest-mongodb
    - StrEnum
    - ophyd-registry >= 0.7
    - xraydb >=4.5.0
    - pytest-timeout  # Get rid of this if tests are not hanging
    # - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
    # --- optional Bluesky framework packages for evaluation
    # - bluesky-webclient is NOT Python software, don't install it this way
    #    https://github.com/bluesky/bluesky-webclient
