# Defaults go here, then get updated by toml loader
[beamline]

name = "SPC Beamline (sector unknown)"
ioc_prefix = ""
vme_prefix = ""
is_connected = false

[facility]

name = "Advanced Photon Source"
xray_source = "insertion device"

[queueserver]
kafka_topic = "s100idc_queueserver"
control_host = "localhost"
control_port = "60615"
info_host = "localhost"
info_port = "60625"

[database.databroker]

catalog = "bluesky"

[shutter]

[shutter.A]

open_pv = "PSS:99ID:FES_OPEN_EPICS.VAL"
close_pv = "PSS:99ID:FES_CLOSE_EPICS.VAL"
status_pv = "PSS:99ID:A_BEAM_PRESENT"

[undulator]

ioc = "id_ioc"

[monochromator]

ioc = "mono_ioc"
ioc_branch = "UP"  # For caQtDM macros

[ion_chamber]

[ion_chamber.scaler]
ioc = "scaler_ioc"
record = "scaler1"

[ion_chamber.preamp]

ioc = "preamp_ioc"

# Keys for ion_chamber definitions must begin with "ch" (e.g. "ch1", "ch2")

[ion_chamber.ch2]

preamp_record = "SR570_1"

[fluorescence_detector]

[fluorescence_detector.vortex]

pv_prefix = ""

# Motors
# ======
# 
# Add a new section for each IOC (or IOC prefix) that has motors
# matching the format {prefix}:m1. The heading of the subsection
# ("VME_crate" in the example below) is a human-readable name that
# will become a label on the Ophyd Device. *num_motors* determines how
# many motors will be read. The example below will load three motors
# with PVs: "vme_crate_ioc:m1", "vme_crate_ioc:m2", and
# "vme_crate_ioc:m3".
[motor.VME_crate]
prefix = "vme_crate_ioc"
num_motors = 3

# Cameras
# =======

[camera]

imagej_command = "imagej"

# Keys for camera definitions must begin with "cam" (e.g. "camA", "camB")
[camera.camA]

name = "s25id-gige-A"
description = "GigE Vision A"
ioc = "camA_ioc"

[stage.Aerotech]

prefix = "vme_crate_ioc"
pv_vert = ":m1"
pv_horiz = ":m2"