# Defaults go here, then get updated by toml loader
[beamline]

name = "SPC Beamline (sector unknown)"
is_connected = false

[facility]

name = "Advanced Photon Source"
xray_source = "insertion device"

[database.databroker]

catalog = "bluesky"

# Cameras
# =======

[camera]

imagej_command = "imagej"
